Las columnas land_area, armed_forces_size, co2-emissions, gdp, population, urban_population, latitude, longitude, density, cpi son de tipo object pero en realidad deberían ser numéricas. Crea una función que nos permita cambiar el tipo de dato de estas columnas al que le corresponde.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_world=pd.read_csv("world_data_full (1).csv",index_col=0)

In [4]:
df_world.head().T

,0,1,2,3,4
country,Afghanistan,Albania,Algeria,Andorra,Angola
density,60,105,18,164,26
abbreviation,AF,AL,DZ,AD,AO
agricultural_land,58.1,43.1,17.4,40.0,47.5
land_area,"652,230","28,748","2,381,741",468,"1,246,700"
armed_forces_size,"323,000","9,000","317,000",NaN,"117,000"
birth_rate,32.49,11.78,24.28,7.2,40.73
calling_code,93.0,355.0,213.0,376.0,244.0
capital/major_city,Kabul,Tirana,Algiers,Andorra la Vella,Luanda
co2-emissions,"8,672","4,536","150,006",469,"34,693"
cpi,149.9,119.05,151.36,NaN,261.73
cpi_change,2.3,1.4,2.0,NaN,17.1
currency-code,AFN,ALL,DZD,EUR,AOA
fertility_rate,4.47,1.62,3.02,1.27,5.52
forested_area,2.1,28.1,0.8,34.0,46.3
gasoline_price,0.7,1.36,0.28,1.51,0.97
gdp,"19,101,353,833","15,278,077,447","169,988,236,398","3,154,057,987","94,635,415,870"
gross_primary_education_enrollment,104.0,107.0,109.9,106.4,113.5
gross_tertiary_education_enrollment,9.7,55.0,51.4,NaN,9.3
infant_mortality,47.9,7.8,20.1,2.7,51.6
largest_city,Kabul,Tirana,Algiers,Andorra la Vella,Luanda
life_expectancy,64.5,78.5,76.7,NaN,60.8
maternal_mortality_ratio,638.0,15.0,112.0,NaN,241.0
minimum_wage,0.43,1.12,0.95,6.63,0.71
official_language,Pashto,Albanian,Arabic,Catalan,Portuguese
out_of_pocket_health_expenditure,78.4,56.9,28.1,36.4,33.4
physicians_per_thousand,0.28,1.2,1.72,3.33,0.21
population,"38,041,754","2,854,191","43,053,054","77,142","31,825,295"
population_labor_force_participation,48.9,55.7,41.2,NaN,77.5
tax_revenue,9.3,18.6,37.2,NaN,9.2
total_tax_rate,71.4,36.6,66.1,NaN,49.1
unemployment_rate,11.12,12.33,11.7,NaN,6.89
urban_population,"9,797,273","1,747,593","31,510,100","67,873","21,061,025"
latitude,33.93911,41.153332,28.033886,42.506285,-11.202692
longitude,67.709953,20.168331,1.659626,1.521801,17.873887

In [8]:
df_world[["land_area", "armed_forces_size", "co2-emissions", "gdp", "population", "urban_population", "latitude", "longitude", "density", "cpi"]]
#

,land_area,armed_forces_size,co2-emissions,gdp,population,urban_population,latitude,longitude,density,cpi
0,"652,230","323,000","8,672","19,101,353,833","38,041,754","9,797,273",33.93911,67.709953,60,149.9
1,"28,748","9,000","4,536","15,278,077,447","2,854,191","1,747,593",41.153332,20.168331,105,119.05
2,"2,381,741","317,000","150,006","169,988,236,398","43,053,054","31,510,100",28.033886,1.659626,18,151.36
3,468,NaN,469,"3,154,057,987","77,142","67,873",42.506285,1.521801,164,NaN
4,"1,246,700","117,000","34,693","94,635,415,870","31,825,295","21,061,025",-11.202692,17.873887,26,261.73
...,...,...,...,...,...,...,...,...,...,...
190,"912,050","343,000","164,175","482,359,318,768","28,515,829","25,162,368",6.42375,-66.58973,32,"2,740.27"
191,"331,210","522,000","192,668","261,921,244,843","96,462,106","35,332,140",14.058324,108.277199,314,163.52
192,"527,968","40,000","10,609","26,914,402,224","29,161,922","10,869,523",15.552727,48.516388,56,157.58
193,"752,618","16,000","5,141","23,064,722,446","17,861,030","7,871,713",-13.133897,27.849332,25,212.31
194,"390,757","51,000","10,983","21,440,758,800","14,645,468","4,717,305",-19.015438,29.154857,38,105.51

In [13]:
df_world["cpi"].unique()

<StringArray>
[   '149.9',   '119.05',   '151.36',        nan,   '261.73',   '113.81',
   '232.75',   '129.18',    '119.8',   '118.06',
 ...
   '114.52',   '119.62',   '117.24',   '202.92',   '117.13', '2,740.27',
   '163.52',   '157.58',   '212.31',   '105.51']
Length: 176, dtype: str

In [ ]:
#hemos analizado que en varias columnas hay nulos.
#todas las columnas son de tipo string pero estamos trabajando con numeros con lo que tenemos que convertir a numero y a floats aquellas que tienen que conservar  su tipo decial
#float-->>land_area,co2-emissions,gp d,latitud,longitud,cpi
#int--> armed_forces_size(hay nulos),population,urban_population,density

In [18]:
#procedemos a cambiar las comas por los puntos.
df_world = df_world.replace(".",",")
df_world.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,...,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
0,Afghanistan,60,AF,58.1,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.4,0.28,"38,041,754",48.9,9.3,71.4,11.12,"9,797,273",33.93911,67.709953
1,Albania,105,AL,43.1,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.9,1.20,"2,854,191",55.7,18.6,36.6,12.33,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.4,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.1,1.72,"43,053,054",41.2,37.2,66.1,11.70,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.0,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.4,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.5,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.4,0.21,"31,825,295",77.5,9.2,49.1,6.89,"21,061,025",-11.202692,17.873887

In [21]:
int=["armed_forces_size","population","urban_population","density"]
float=["land_area","co2-emissions","gpd","latitud","longitud","cpi"]

In [ ]:
def limpieza(dato):
    
    datos_limpios=str(dato).replace(",",".")
    try:
        return float(datos_limpios)
    except:
        return float("nan")

In [ ]:
#ahora le decimos que si esta en la lista int que los convierta a int si no que los convierta a float y luego lo hacemos mediante aply.


Crea una función para añadir una nueva columna llamada 'Continent' al DataFrame para indicar a qué continente pertenece cada país.

In [2]:
df_world = pd.read_csv("world_data_full.csv", index_col=0)
df_world.head(2)

NameError: name 'pd' is not defined

In [ ]:
continentes = {
    'Asia': ["Philippines", 'Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'East Timor', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'North Korea', 'Oman', 'Pakistan', 'Palestinian National Authority', 'Qatar', 'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Tajikistan', 'Thailand', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen'],
    'Africa': ["Tunisia", "Ivory Coast", 'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cape Verde', 'Cameroon', 'Central African Republic', 'Chad', 'Comoros', 'Republic of the Congo', 'Cote d\'Ivoire', 'Democratic Republic of the Congo', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon', 'The Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Tanzania', 'Togo', 'Uganda', 'Zambia', 'Zimbabwe'],
    'Europe': ["Turkey", "Republic of Ireland", "Vatican City", 'Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Ukraine', 'United Kingdom'],
    "Central America":["Belize", "Saint Vincent and the Grenadines", "Saint Lucia", "Saint Kitts and Nevis", "Panama", "Nicaragua", "Mexico", "Jamaica", "Honduras", "Haiti", "Guatemala", "Grenada", "El Salvador", "Dominican Republic", "Dominica", "Cuba", "Antigua and Barbuda", "The Bahamas", "Barbados"," Belize", "Costa Rica",  ], 
    'North America': ['Canada', 'United States'],
    'South America': ["Trinidad and Tobago", 'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela'],
    'Oceania': ["Papua New Guinea", "Federated States of Micronesia", 'Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Nauru', 'New Zealand', 'Palau', 'Samoa', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu']
}

In [ ]:
test="afganistan"

In [ ]:
def continente(pais):
    continentes = {
    'Asia': ["Philippines", 'Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'East Timor', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'North Korea', 'Oman', 'Pakistan', 'Palestinian National Authority', 'Qatar', 'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Tajikistan', 'Thailand', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen'],
    'Africa': ["Tunisia", "Ivory Coast", 'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cape Verde', 'Cameroon', 'Central African Republic', 'Chad', 'Comoros', 'Republic of the Congo', 'Cote d\'Ivoire', 'Democratic Republic of the Congo', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon', 'The Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Tanzania', 'Togo', 'Uganda', 'Zambia', 'Zimbabwe'],
    'Europe': ["Turkey", "Republic of Ireland", "Vatican City", 'Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Ukraine', 'United Kingdom'],
    "Central America":["Belize", "Saint Vincent and the Grenadines", "Saint Lucia", "Saint Kitts and Nevis", "Panama", "Nicaragua", "Mexico", "Jamaica", "Honduras", "Haiti", "Guatemala", "Grenada", "El Salvador", "Dominican Republic", "Dominica", "Cuba", "Antigua and Barbuda", "The Bahamas", "Barbados"," Belize", "Costa Rica",  ],
    'North America': ['Canada', 'United States'],
    'South America': ["Trinidad and Tobago", 'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela'],
    'Oceania': ["Papua New Guinea", "Federated States of Micronesia", 'Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Nauru', 'New Zealand', 'Palau', 'Samoa', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu']
}
    for k, v in continentes.items():
        if pais in v:
            return k
    return np.nan

In [ ]:
lat = 33.93911
lon = 67.709953

In [ ]:
def lat_lon(latitud, longitud):
    return tuple((latitud, longitud))
lat_lon(lat, lon)
df_world["continent_2"] = df_world.apply(lambda fila: continente_2(fila["country"], continentes), axis=1)

In [ ]:
df_world["lat_lon"] = df_world.apply(lambda fila: lat_lon(fila["latitude"], fila["longitude"]), axis = 1)