In [1]:
import pandas as pd
import numpy as np

In [ ]:
df_world_data = pd.read_csv("world_data.csv",index_col=0)
df_world_data.head(5) # muestra las 5 primeras filas

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [ ]:
df_world_data.sample(5) # muestra 5 aleatorias

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
27,Burundi,463,BI,79.20%,"27,830","31,000",39.01,257.0,Bujumbura,495,182.11,-0.70%,BIF,5.41,10.90%,$1.21
188,Uzbekistan,79,UZ,62.90%,"447,400","68,000",23.30,998.0,Tashkent,"91,811",NaN,NaN,UZS,2.42,7.50%,$1.03
171,Tajikistan,68,TJ,34.10%,"144,100","17,000",30.76,992.0,Dushanbe,"5,310",148.57,6.00%,TJS,3.59,3.00%,$0.71
40,Costa Rica,100,CR,34.50%,"51,100","10,000",13.97,506.0,San Jos������,"8,023",128.85,2.10%,CRC,1.75,54.60%,$0.98
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00

In [ ]:
df_world_data.tail(5) # muestra las 5 ultimas filas, suelen ser por defecto 5

In [ ]:
df_world_data.columns # nos muestra el nombre de las columnas.

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price'],
      dtype='str')

In [ ]:
df_world_data["Abbreviation"].unique() #mostramos los valores unicos de la columna abbreviation.

<StringArray>
['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT',
 ...
 'GB', 'US', 'UY', 'UZ', 'VU', 'VE', 'VN', 'YE', 'ZM', 'ZW']
Length: 189, dtype: str

In [ ]:
df_world_data["Abbreviation"].nunique()# aqui nos muestra cuantas veces aparece cada valor unico en la columna seleccionada.

188

In [14]:
# ahora vamos a ver los nulos de todo el dataframe.
df_world_data.isnull().sum()

Country                   0
Density\n(P/Km2)          0
Abbreviation              7
Agricultural Land( %)     7
Land Area(Km2)            1
Armed Forces size        24
Birth Rate                6
Calling Code              1
Capital/Major City        3
Co2-Emissions             7
CPI                      17
CPI Change (%)           16
Currency-Code            15
Fertility Rate            7
Forested Area (%)         7
Gasoline Price           20
dtype: int64

In [ ]:
df_world_data.notnull().sum() # aqui vemos los valores que no son nulos

Country                  195
Density\n(P/Km2)         195
Abbreviation             188
Agricultural Land( %)    188
Land Area(Km2)           194
Armed Forces size        171
Birth Rate               189
Calling Code             194
Capital/Major City       192
Co2-Emissions            188
CPI                      178
CPI Change (%)           179
Currency-Code            180
Fertility Rate           188
Forested Area (%)        188
Gasoline Price           175
dtype: int64

In [16]:
df_world_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                195 non-null    str
 1   Density
(P/Km2)        195 non-null    str
 2   Abbreviation           188 non-null    str
 3   Agricultural Land( %)  188 non-null    str
 4   Land Area(Km2)         194 non-null    str
 5   Armed Forces size      171 non-null    str
 6   Birth Rate             189 non-null    float64
 7   Calling Code           194 non-null    float64
 8   Capital/Major City     192 non-null    str
 9   Co2-Emissions          188 non-null    str
 10  CPI                    178 non-null    str
 11  CPI Change (%)         179 non-null    str
 12  Currency-Code          180 non-null    str
 13  Fertility Rate         188 non-null    float64
 14  Forested Area (%)      188 non-null    str
 15  Gasoline Price         175 non-null    str
dtypes: float64(3), str(13)
memory usage: 24.5 KB

In [ ]:
df_world_data1 = df_world_data.drop(columns="Armed Forces size") # este metodo creamos una variable antes de borrar.
df_world_data1.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Birth Rate', 'Calling Code', 'Capital/Major City',
       'Co2-Emissions', 'CPI', 'CPI Change (%)', 'Currency-Code',
       'Fertility Rate', 'Forested Area (%)', 'Gasoline Price'],
      dtype='str')

In [21]:
df_world_data.drop(columns="Armed Forces size",inplace=True) # aqui borramos directamente sin guardar copia

In [ ]:
df_world_data.describe() #mostramos todas las estadisticas.

       Birth Rate  Calling Code  Fertility Rate
count  189.000000    194.000000      188.000000
mean    20.214974    360.546392        2.698138
std      9.945774    323.236419        1.282267
min      5.900000      1.000000        0.980000
25%     11.300000     82.500000        1.705000
50%     17.950000    255.500000        2.245000
75%     28.750000    506.750000        3.597500
max     46.080000   1876.000000        6.910000

In [ ]:
#vamos hacer algun extra:vamos  a ver el porcentaje de nulos que tenemos en nuestro csv.redondeamos a 2 decimales.
round(df_world_data.isnull().sum()/df_world_data.shape[0]*100,2)

Country                   0.00
Density\n(P/Km2)          0.00
Abbreviation              3.59
Agricultural Land( %)     3.59
Land Area(Km2)            0.51
Birth Rate                3.08
Calling Code              0.51
Capital/Major City        1.54
Co2-Emissions             3.59
CPI                       8.72
CPI Change (%)            8.21
Currency-Code             7.69
Fertility Rate            3.59
Forested Area (%)         3.59
Gasoline Price           10.26
dtype: float64

In [ ]:
df_world_data.describe(exclude=np.number).T # aqui estamos viendo la informacion de las columnas categoricas.

                      count unique          top freq
Country                 195    195  Afghanistan    1
Density\n(P/Km2)        195    137           25    7
Abbreviation            188    188           AF    1
Agricultural Land( %)   188    168       17.40%    3
Land Area(Km2)          194    194      652,230    1
Capital/Major City      192    192        Kabul    1
Co2-Emissions           188    184          495    2
CPI                     178    175       106.58    2
CPI Change (%)          179     86        1.80%    7
Currency-Code           180    133          EUR   23
Forested Area (%)       188    161       32.70%    3
Gasoline Price          175    101       $0.71     6